apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" $.Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ printf "%s-deployment" $.Release.Name | trunc 63 | trimSuffix "-" }}
  ports:
    - name: http
      port: 80
      targetPort: http
